### ISSUE TITLE
Deleted Message Tracker

### ISSUE THREAD

**Issue by CS-5** [PulseDevelopmentGroup/0x626f74#4]
Track last 25(?) messages in each channel. If a message is deleted, inform the channel who deleted a message.

Potential other features:

- [ ] Send the deleted message
- [ ] Give a user a 3 strikes system (After 3 strikes they are kicked?)
- [ ] Log deleted message to web dashboard (when/if that exists)

**Comment by CS-5** [comment]
Less of an issue on the server these days. Should this still be a feature? Would require a DB unfortunately.
